// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZHyoILjBVWl1Omt25GOkBOQDrag2rWME',
    appId: '1:620518869063:web:20d1c89edc1b76a6560962',
    messagingSenderId: '620518869063',
    projectId: 'dukkantek-1a2a3',
    authDomain: 'dukkantek-1a2a3.firebaseapp.com',
    storageBucket: 'dukkantek-1a2a3.appspot.com',
    measurementId: 'G-BFCJXSCJ80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlKjnLPRUe9yzGVfPDPJDjpuCr6t_sxj4',
    appId: '1:620518869063:android:949399f051a42825560962',
    messagingSenderId: '620518869063',
    projectId: 'dukkantek-1a2a3',
    storageBucket: 'dukkantek-1a2a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTqCE6MIurmBnOH2S4_9om7Kw9N_TfYg',
    appId: '1:620518869063:ios:0ff04687d0b52b02560962',
    messagingSenderId: '620518869063',
    projectId: 'dukkantek-1a2a3',
    storageBucket: 'dukkantek-1a2a3.appspot.com',
    iosClientId: '620518869063-1hh6bh5asc0lva474j5gq27qdpre9tnb.apps.googleusercontent.com',
    iosBundleId: 'com.dukkantek.interview',
  );
}
